# Generated by Django 4.1.7 on 2023-02-26 06:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceFormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SALESFORCE", "Salesforce"),
                            ("GOOGLE_SHEETS", "Google Sheets"),
                            ("FRESHDESK", "Freshdesk"),
                            ("SHOPIFY", "Shopify"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("source_form", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("source_form_data", models.JSONField()),
                ("company_id", models.IntegerField()),
                (
                    "source_form_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_data.sourceformtemplate",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("company_id", "source_form_template"),
                name="unique_source_form_for_company",
            ),
        ),
    ]
