# Generated by Django 4.1.7 on 2023-02-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceformtemplate',
            old_name='source_form',
            new_name='fields',
        ),
        migrations.RenameField(
            model_name='sourceformtemplate',
            old_name='source_type',
            new_name='type',
        ),
    ]
